version: '3'

services:
  django-nginx-gunicorn:
    container_name: Django-production
    image: ifm7/django-production:latest
    networks:
      - django-production
    ports:
      - 8000:8000
    volumes:
      - ../django-data:/django-data:rwxrwxr-w
      - ./docker-data/django/:/docker-data/
    command: /docker-data/django-init-production.sh
    restart: always
    depends_on:
      - postgres

  postgres:
    container_name: Django-production-postgres
    # image: ifm7/django-production-pg-db
    image: postgres:16-alpine3.18
    networks:
      - django-production
    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_USER: postgres
      POSTGRES_DB: pdb
    ports:
      - 5432:5432
    volumes:
      - ./docker-data/postgres/:/docker-data/
    command: /docker-data/postgres-init-production.sh

volumes:
  django-data:
  postgresql-conf:

networks:
  django-production:
    driver: bridge