version: '3'

services:
  django-nginx-gunicorn:
    container_name: Django-production
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - django-production
    ports:
      - 8000:8000
    volumes:
      - ./django-data:/django-data:rwxrwxr-w
    command: /django-init-production.sh
    restart: always
    depends_on:
      - postgres

  postgres:
    container_name: Django-production-postgres
    build:
      context: .
      dockerfile: Dockerfile-postgres
    networks:
      - django-production
    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_USER: postgres
      POSTGRES_DB: pdb
    ports:
      - 5432:5432
    volumes:
      - ./postgres-conf:/etc/postgresql
    command: /postgres-init-production.sh

volumes:
  django-data:
  postgres-conf:

networks:
  django-production:
    driver: bridge